-- DXT P08 canonical runtime extraction
-- Classification: CANONICAL
-- Source verified from live Supabase runtime on 2026-07-25.

create or replace view public.ui_margin_decision_workspace_v2
with (security_invoker = true)
as
select
    owner_email,
    run_id,
    upload_batch_id,
    is_latest_run,
    run_status,
    data_readiness_status,
    run_completed_at,
    recommendation_id,
    selected_candidate_id,
    support_pack_id,
    decision_position,
    total_decision_count,
    priority_level,
    priority_score,
    priority_display,
    priority_explanation,
    decision_title,
    decision_subject_primary,
    decision_subject_secondary,
    entity_primary,
    entity_secondary,
    category_primary,
    category_secondary,
    recommended_move,
    target_change_display,
    diagnosis,
    root_cause_name,
    because_summary,
    prescriptive_summary,
    selection_explanation,
    tradeoff_risk,
    implementation_note,
    estimated_financial_impact,
    estimated_financial_impact_display,
    financial_impact_type,
    financial_impact_score,
    financial_impact_score_display,
    confidence_score,
    confidence_percent,
    confidence_display,
    confidence_explanation,
    current_state_value,
    current_state_display,
    recommended_target_value,
    recommended_target_display,
    monthly_impact_estimate,
    ninety_day_impact_estimate,
    annualized_impact_estimate,
    support_status_code,
    support_status_label,
    support_status_tone,
    support_display,
    source_record_count,
    validated_source_count,
    pending_validation_count,
    support_fact_count,
    confidence_support_state,
    confidence_support_explanation,
    support_data_quality_score,
    support_data_quality_level,
    blocking_data_gap,
    validation_required,
    validation_summary,
    decision_support_updated_at,
    decision_status_internal,
    decision_status_code,
    decision_status_label,
    decision_status_tone,
    decision_status_message,
    next_action_code,
    next_action_label,
    next_action_is_executable,
    available_action_count,
    executable_action_count,
    primary_action_code,
    primary_action_label,
    primary_action_is_executable,
    secondary_action_code,
    secondary_action_label,
    secondary_action_is_executable,
    has_executable_action,
    action_availability_code,
    has_leading_alternative,
    alternative_candidate_id,
    alternative_move,
    alternative_target_value,
    alternative_estimated_financial_impact,
    alternative_financial_impact_type,
    alternative_recommendation_score,
    alternative_tradeoff_risk,
    alternative_support_summary,
    alternative_reason_not_selected,
    platform_domain,
    engine_conflict_type,
    conflict_code,
    conflict_status,
    policy_conflict_classification,
    data_block_classification,
    has_matching_policy_setting,
    recommendation_created_at,
    recommendation_updated_at,
    recommendation_code
from public.out_margin_decision_workspace_v2;

alter view public.ui_margin_decision_workspace_v2 owner to postgres;
revoke all on public.ui_margin_decision_workspace_v2 from anon;
grant select on public.ui_margin_decision_workspace_v2 to authenticated;
grant select on public.ui_margin_decision_workspace_v2 to service_role;
comment on view public.ui_margin_decision_workspace_v2 is
'WeWeb-facing Decision Review workspace v2 contract for the clean DXT build. One row per latest-run decision; selection remains frontend state keyed by recommendation_id.';
