-- DXT P08 canonical runtime extraction
-- Classification: CANONICAL
-- Source verified from live Supabase runtime on 2026-07-25.

create or replace view public.ui_margin_portfolio_decision_v2
with (security_invoker = true)
as
select
    owner_email,
    run_id,
    upload_batch_id,
    is_latest_run,
    run_status,
    data_readiness_status,
    run_completed_at,
    total_decision_count,
    decision_position,
    is_top_priority,
    recommendation_id,
    selected_candidate_id,
    priority_level,
    priority_score,
    sku,
    sku_name,
    scope_display_primary,
    scope_display_secondary,
    scope_coverage_display,
    affected_order_count,
    affected_sku_count,
    decision_title,
    recommended_move,
    recommendation_type,
    recommendation_code,
    business_lever,
    current_state_value,
    recommended_target_value,
    current_state_display,
    recommended_target_display,
    target_change_display,
    affected_entity_type,
    affected_entity_id,
    affected_entity_name,
    entity_primary,
    entity_secondary,
    category_primary,
    category_secondary,
    leak_type,
    root_cause_name,
    diagnosis,
    because_summary,
    prescriptive_summary,
    estimated_financial_impact,
    estimated_financial_impact_display,
    financial_impact_type,
    financial_impact_score,
    financial_impact_score_display,
    confidence_score,
    confidence_percent,
    confidence_display,
    monthly_impact_estimate,
    ninety_day_impact_estimate,
    annualized_impact_estimate,
    support_status_code,
    support_status_label,
    support_status_tone,
    support_display,
    source_record_count,
    validation_required,
    blocking_data_gap,
    recommendation_data_quality_level,
    support_data_quality_level,
    data_quality_score,
    support_summary,
    selection_explanation,
    confidence_explanation,
    tradeoff_risk,
    implementation_note,
    alternative_candidate_id,
    alternative_move,
    alternative_target_value,
    alternative_estimated_financial_impact,
    alternative_impact_type,
    alternative_recommendation_score,
    alternative_tradeoff_risk,
    alternative_support_summary,
    alternative_reason_not_selected,
    has_leading_alternative,
    decision_status_internal,
    decision_status_code,
    decision_status_label,
    decision_status_tone,
    decision_status_message,
    next_action_label,
    next_action_code,
    next_action_is_executable,
    decision_priority_display,
    priority_explanation,
    search_text,
    recommendation_created_at,
    recommendation_updated_at,
    platform_domain,
    engine_conflict_type,
    conflict_code,
    conflict_status,
    policy_conflict_classification,
    data_block_classification,
    has_matching_policy_setting
from public.out_margin_portfolio_decision_v2;

alter view public.ui_margin_portfolio_decision_v2 owner to postgres;
revoke all on public.ui_margin_portfolio_decision_v2 from anon;
grant select on public.ui_margin_portfolio_decision_v2 to authenticated;
grant select on public.ui_margin_portfolio_decision_v2 to service_role;
comment on view public.ui_margin_portfolio_decision_v2 is
'WeWeb-facing Decision Portfolio decision-row v2 contract for clean DXT builds. New frontend bindings should use this contract rather than extending the legacy decision projection.';
